spring.application.name=auth-service
server.port=8083

# ========================
# EUREKA CLIENT CONFIG
# ========================
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/
eureka.instance.prefer-ip-address=true

# ========================
# SECURITY / KEYCLOAK CONFIG
# ========================
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://keycloak:8080/realms/snippix-realm
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://keycloak:8080/realms/snippix-realm/protocol/openid-connect/certs

# ========================
# KEYCLOAK ADMIN CONFIG
# ========================
keycloak.server-url=http://keycloak:8080
keycloak.realm=snippix-realm

keycloak.admin.client-id=snippix-gateway-client
keycloak.admin.client-secret=IKbJpCJQG7rsxd8KCjhdguKpie1fLLe9
keycloak.admin.username=admin
keycloak.admin.password=admin

# ========================
# GRPC CLIENT CONFIG
# ========================
grpc.client.user-service.address=static://user-service:9090
grpc.client.user-service.negotiationType=plaintext

# ========================
# Redis Configuration
# ========================

spring.data.redis.host=redis
spring.data.redis.port=6379
spring.data.redis.timeout=60000